apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
spec:
  selector:
    matchLabels:
      app: mail
  replicas: 1
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: mail
        image: mailhog/mailhog:v1.0.1
        env:
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: user_name
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: password
        - name: MAIL_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: mail-cfgmap
              key: MAIL_DOMAIN
        - name: MAIL_DEFAULT_SENDER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: mail-cfgmap
              key: MAIL_DEFAULT_SENDER_ADDRESS
        - name: MAIL_DEFAULT_SENDER_NAME
          valueFrom:
            configMapKeyRef:
              name: mail-cfgmap
              key: MAIL_DEFAULT_SENDER_NAME
        ports:
        - containerPort: 1025
          name: mail
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail
  type: LoadBalancer
  ports:
  - port: 1025
    targetPort: 1025